# Generated by Django 4.2.1 on 2023-12-23 12:51

from django.db import migrations

from django.db import migrations

def create_categories(apps, schema_editor):
    Category = apps.get_model('capsules', 'Category')
    categories = [
        (1, 'Mindfulness'),
        (2, 'Personal Growth'),
        (3, 'Creativity'),
        (4, 'Motivation'),
        (5, 'Relationships'),
        (6, 'Wellness'),
        (7, 'Others'),
    ]
    for category_id, category_name in categories:
        Category.objects.create(id=category_id, name=category_name)

class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0002_category_capsule_categories'),
    ]

    operations = [
        migrations.RunPython(create_categories),
    ]
